### ISSUE TITLE
User can create a profile

### ISSUE THREAD

**Issue by rachelbeacham** [rachelbeacham/code-journal#1]
## 💰 Motivation

Users like to personalize things! 😄

## 📐 Plan

Create a responsive form for users to enter their profile details into and save their data to local storage.

## 🖼️ Wireframe

![user can create a profile](https://lfz-static.s3-us-west-1.amazonaws.com/graphics/wireframes/code-journal/user-can-create-a-profile.png)

## ✅ Task List

- [x] Pick a nice font pair from Google Fonts for headings and body text.
- [x] Pick a nice accent color.
- [x] Create a simple, polished header in HTML and CSS that shows the name of the application.
- [x] Create a simple, polished form in the HTML and CSS that shows a placeholder image for the avatar.
- [x] Apply fonts to the heading, labels, and form inputs.
- [x] Check to make sure that the form looks good on mobile and desktop.
- [x] Make all form inputs `required`.
- [x] Make the `name` attributes of the form input elements match the keys of the profile data model.
- [x] Listen for `'input'` events on the avatar url input.
- [x] Update the avatar preview image's `src` when the avatar url input changes.
- [x] Listen for `'submit'` events on the form.
- [x] Assign all of the form's values into the profile data model when the form is submitted.
- [x] Reset the form inputs when the form is submitted.
- [x] Reset the avatar preview image when the form is submitted.
- [x] Make sure that the user's data is persisted to local storage between reloads.
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again.
