### ISSUE TITLE
User can view their profile

### ISSUE THREAD

**Issue by rachelbeacham** [rachelbeacham/code-journal#2]
## 💰 Motivation

Users will want to check what information they have told us about themselves.

## 📐 Plan

Create a separate view that dynamically renders the user's profile details.

## 🖼️ Wireframe

![user can view their profile](https://lfz-static.s3-us-west-1.amazonaws.com/graphics/wireframes/code-journal/user-can-view-their-profile.png)

## ✅ Task List

- [x] Hide the `div[data-view="edit-profile"]` view in the HTML.
- [x] Add a new `div[data-view="profile"]` to the HTML to display the user's profile information.
- [x] Build an example profile in the `data-view="profile"` with HTML and CSS.
- [x] Ensure that the profile view looks good on both mobile and desktop.
- [x] Define a JavaScript function that takes the profile data model and returns a DOM tree that matches the HTML.
- [x] Define a JavaScript view swapping function that takes the name of which `data-view` to show and hides all others.
- [x] Make the view swapping function also write the name of the view it showed to the application's data model.
- [x] Test the view swapping function by hand in the browser console, passing it `'edit-profile'` or `'profile'` as an argument.
  - [x] Update the view swapping function to empty out the content of the `div[data-view="profile"]` when showing the `'profile'`.
  - [x] Update the view swapping function to append the return value of the profile rendering function to the `div[data-view="profile"]` when showing the `'profile'`.
- [x] Update the `'submit'` event listener on the form to show the `'profile'` view after profile data model has been updated.
- [x] Listen to the `document` for `'DOMContentLoaded'`.
  - [x] If the user has not saved a `username`, show the profile form, otherwise show the `view` that was written to the data model.
  - [x] Use a private browsing tab to test that a new user sees the form when the page loads.
  - [x] Verify that a returning user sees their profile when the page loads.
- [x] Delete the reference profile from the HTML code so that the `div[data-view="profile"]` is initially empty.
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again.
- [x] Fix all bugs.
