### ISSUE TITLE
User can update their profile

### ISSUE THREAD

**Issue by rachelbeacham** [rachelbeacham/code-journal#3]
## 💰 Motivation

Users will want to change their profile information to suit their mood.

## 📐 Plan

Allow users to navigate between their profile and the form to edit their profile details.

## 🖼️ Wireframe

![user can update their profile](https://lfz-static.s3-us-west-1.amazonaws.com/graphics/wireframes/code-journal/user-can-update-their-profile.png)

## ✅ Task List

- [x] Update the view swapping function to pre-populate the profile form and avatar preview when showing the `'edit-profile'` view.
- [x] Test the view swapping function by hand in the browser console.
- [x] Update the profile rendering function to include a link styled as a button with an `href="#"` and a `data-view="edit-profile"`.
- [x] Add a `'click'` listener to the `document` that exits immediately if a link was not clicked.
  - [x] If a link _was_ clicked, show the matching view using the view swapping function.
- [x] Add link to the navbar with an `href="#"` and a `data-view="profile"`.
- [x] Verify that clicking the profile link navigates away from the profile form.
- [x] Block the user from going to the `'profile'` view if they have never saved a `username`.
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test the user flow in a private browsing tab.
- [x] Fix all bugs.
