### ISSUE TITLE
User can create an entry

### ISSUE THREAD

**Issue by rachelbeacham** [rachelbeacham/code-journal#4]
## 💰 Motivation

Coders will want to capture tidbits they pick up during their research.

## 📐 Plan

Create a responsive form that allows users to store an image URL with some notes about a specific topic.

## 🖼️ Wireframe

![user can create an entry](https://lfz-static.s3-us-west-1.amazonaws.com/graphics/wireframes/code-journal/user-can-create-an-entry.png)

## ✅ Task List

- [x] Add a `div[data-view="entries"]` to the HTML.
- [x] Add a link to the navbar to show the `'entries'` view.
- [x] Verify that a user can only see the `'entries'` view if they have a profile already.
- [x] Add a `div[data-view="create-entry"]` to the HTML.
- [x] Add a form for creating a journal entry to the `div[data-view="create-entry"]`.
- [x] Ensure that the form looks nice on both mobile-sized and desktop-sized screens.
- [x] Make all inputs of the journal entry form `required`.
- [x] Add a link to the `'entries'` view that navigates the user to the `'create-entry'` view.
- [x] Listen for `'input'` events on the `photoUrl` input to update the photo preview when the input value changes.
- [x] Listen for `'submit'` events on the journal entry form and:
  - [x] Put the form's input values into a new object.
  - [x] Prepend the new object to the entries in the data model.
  - [x] Reset the image preview's `src' attribute.
  - [x] Reset the form inputs.
  - [x] Show the `'entries'` view again.
- [x] Verify that new entries are saved to local storage along with the rest of the data model on reload.
- [x] Verify that a brand new user cannot go to the `'entries'` view if they haven't created their profile.
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again.
- [x] Fix all bugs.
