### ISSUE TITLE
User can view their entries

### ISSUE THREAD

**Issue by rachelbeacham** [rachelbeacham/code-journal#5]
## 💰 Motivation

Once a user records a journal entry, they'll want to revisit it again.

## 📐 Plan

Display the user's journal entries in reverse chronological order so they can see the newest ones first.

## 🖼️ Wireframe

![user can view their entries](https://lfz-static.s3-us-west-1.amazonaws.com/graphics/wireframes/code-journal/user-can-view-their-entries.png)

## ✅ Task List

- [x] Add an empty ordered list element to the `div[data-view="entries"]`.
- [x] Add some dummy journal entries to the HTML and style them to match the wireframe.
- [x] Check that the entries list looks good on both mobile and desktop screens.
- [x] Define a function that takes a single journal entry object and returns a DOM tree that matches one of the example entries in the HTML.
- [x] Create a DOM tree for each journal entry in the data model and append it to the page when the `'DOMContentLoaded'` event is fired.
- [x] Remove the example HTML entries once the user's entries are successfully being appended.
- [x] Ensure that submitting a new journal entry also creates a new DOM tree for it and adds it to the page.
- [x] Clean up all unnecessary styling.
- [x] Test the user flow in a private browsing tab.
- [x] Fix all bugs.
